version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql
    volumes:
      - mysql_data_1:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  mysql_data:
    image: mysql:5.7.38
    volumes:
      - mysql_data_2:/var/lib/mysql
    ports:
        - "3308:3306"
    environment:
        MYSQL_DATABASE: stationery-chain
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: root
volumes:
  mysql_data_1:
  mysql_data_2: