server:
  port: 8080

keycloak:
  realm: stationery-realm
  auth-server-url: http://localhost:8180/auth/
  resource: react-client
  bearer-only: true
  public-client: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3308/stationery-chain
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect